[features]
seeds = false

[programs.localnet]
formfn_candy_machine = "gachaC2NGh63y4ogLK8xHLeB5ZFZ8ypDLXEQyKNm8sy"

[programs.devnet]
formfn_candy_machine = "gachaC2NGh63y4ogLK8xHLeB5ZFZ8ypDLXEQyKNm8sy"

[programs.testnet]
formfn_candy_machine = "gachaC2NGh63y4ogLK8xHLeB5ZFZ8ypDLXEQyKNm8sy"

[registry]
url = "https://anchor.projectserum.com"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "artifacts/mpl_token_metadata.so"

[provider]
cluster = "devnet"
wallet = "keys/devnet/deployer-keypair.json"

[workspace]
members = [
  "programs/formfn-candy-machine",
]

[scripts]
test = "./scripts/test-local.sh"